//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAlliance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admini
    {
        public int AdminiID { get; set; }
        public string AdminiPhone { get; set; }
        public string AdminiName { get; set; }
        public string AdminiPassword { get; set; }
        public string AdminiAvatar { get; set; }
    }
}
