//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAlliance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public string CommentUser { get; set; }
        public string CommentContent { get; set; }
        public Nullable<System.DateTime> CommentonTime { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
