//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAlliance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodID { get; set; }
        public Nullable<int> TypessID { get; set; }
        public string FoodName { get; set; }
        public string FoodPicture { get; set; }
        public string FoodRecommend { get; set; }
        public string FoodPractce { get; set; }
    
        public virtual Typess Typess { get; set; }
    }
}
