//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodAlliance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int RecipeID { get; set; }
        public string RecipeName { get; set; }
        public Nullable<int> TypessID { get; set; }
        public string RecipePicture { get; set; }
        public string RecipeDifficulty { get; set; }
        public string RecipeTime { get; set; }
        public string RecipeStory { get; set; }
        public string Ingredient { get; set; }
        public string RecipeDosage { get; set; }
        public string FlowChart { get; set; }
        public string Particular { get; set; }
        public Nullable<int> ThumbNumber { get; set; }
        public Nullable<int> UsersID { get; set; }
        public int Audit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Typess Typess { get; set; }
        public virtual Users Users { get; set; }
    }
}
